export interface Pokemon {
  id: number,
  img: string,
  name: string,
  types: string[]
  weight: number,
  height: number,
  hp: number,
  attack: number,
  defense: number,
  speed: number,
  exp: number,
}
export const colors: {[key:string]: string} = {
  bug: '#91BA2E',
  dark: '#5F4632',
  dragon: '#8A55FD',
  electric: '#FFFA24',
  fairy: '#FFA0C2',
  fighting: '#E81319',
  fire: '#FC0C0B',
  flying: '#5EB9B2',
  ghost: '#8E55A4',
  grass: '#3E9709',
  ground: '#E1D158',
  ice: '#1995A1',
  normal: '#CCC9AA',
  poison: '#A819D7',
  psychic: '#EC0E63',
  rock: '#776A3E',
  steel: '#7B8E8A',
  water: '#0A7ABC',
}

export const newColors: {[key:string]: string} = {
  "bug": '#179A55',
  "dark": '#040706',
  "dragon": '#378A94',
  "electric": '#E0E64B',
  "fairy": '#9E1A44',
  "fighting": '#9F422A',
  "fire": '#B22328',
  "flying": '#90B1C5',
  "ghost": '#363069',
  "grass": '#007C42',
  "ground": '#AD7235',
  "ice": '#7ECFF2',
  "normal": '#B1A5A5',
  "poison": '#642785',
  "psychic": '#AC296B',
  "rock": '#4B190E',
  "steel": '#5C756D',
  "water": '#2648DC',

  "black": '#000000',
  "yellow": '#FBC02D',
  "skyBlue": '#57A8D8',
  "colorPrimary": '#D53A47',
  "colorPrimaryDark": '#D53A47',
  "colorAccent": '#D53A47',
  "black_70": '#B3000000',
  "white_12": '#fafafa',
  "white_56": '#8effffff',
  "white_70": '#b2ffffff',
  "white_87": '#ddffffff',
  "white_93": '#edf8f8f8',
  "white": '#ffffff',
  "background": '#2B292B',
  "background800": '#424242',
  "background900": '#212121',
  "md_yellow_100": '#FFD600',
  "md_yellow_200": '#FBC02D',
  "md_amber_700": '#FFA000',
  "md_orange_100": '#FFA726',
  "md_orange_200": '#FF6D00',
  "md_green_100": '#81C784',
  "md_green_200": '#388E3C',
  "md_blue_100": '#81D4fA',
  "md_blue_200": '#0091EA',
}

export const namePokemons = [
  "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon",
  "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie",
  "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill",
  "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
  "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu",
  "Raichu", "Sandshrew", "Sandslash", "Nidoran", "Nidorina",
  "Nidoqueen", "Nidoran", "Nidorino", "Nidoking", "Clefairy",
  "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff",
  "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume",
  "Paras", "Parasect", "Venonat", "Venomoth", "Diglett",
  "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck",
  "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag",
  "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam",
  "Machop", "Machoke" ,"Machamp" ,"Bellsprout" ,"Weepinbell",
  "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler",
  "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro",
  "Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio",
  "Seel", "Dewgong", "Grimer", "Muk", "Shellder",
  "Cloyster", "Gastly", "Haunter", "Gengar", "Onix",
  "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb",
  "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak",
  "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing",
  "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan",
  "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu",
  "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz",
  "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados",
  "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon",
  "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto",
  "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos",
  "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo",
  "Mew"
]
